// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace EFCore6Sample.CompiledModels
{
    public partial class PeopleContextModel
    {
        partial void Initialize()
        {
            var bankAccount = BankAccountEntityType.Create(this);
            var person = PersonEntityType.Create(this);

            PersonEntityType.CreateForeignKey1(person, bankAccount);

            BankAccountEntityType.CreateAnnotations(bankAccount);
            PersonEntityType.CreateAnnotations(person);

            AddAnnotation("ProductVersion", "6.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
