// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace EFCore6Sample.CompiledModels
{
    [DbContext(typeof(PeopleContext))]
    public partial class PeopleContextModel : RuntimeModel
    {
        static PeopleContextModel()
        {
            var model = new PeopleContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static PeopleContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
